apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spire

resources:
- spire-namespace.yaml
- agent-account.yaml
- agent-cluster-role.yaml
- agent-configmap.yaml
- agent-daemonset.yaml
- server-account.yaml
- server-cluster-role.yaml
- server-configmap.yaml
- server-service.yaml
- server-statefulset.yaml
- spire-bundle-configmap.yaml
- auto/spiffe-csi-driver.yaml
- auto/leader_election_role.yaml
- auto/leader_election_role_binding.yaml
- auto/spire.spiffe.io_clusterfederatedtrustdomains.yaml
- auto/spire.spiffe.io_clusterspiffeids.yaml
- auto/spire-controller-manager-webhook.yaml

configMapGenerator:
- name: spire-controller-manager-config
  namespace: spire
  files:
  - auto/spire-controller-manager-config.yaml
